#!/usr/bin/env python3
"""Generates Lunacy's libGLES_CM.so for PDK apps from the PDK's own GLES 1.1 headers
(Docs/pdk.md, "Transformers G1"): every `glXxx` the headers declare, as a C function with
the declared signature.

Stage one (this): a *logging* library. Each call is counted and the first few of each are
logged, queries answer plausibly (glGetString, glGetError, glGen*, glGetIntegerv, the OES
framebuffer status), so a GLES 1.1 game runs its whole startup and game loop against it and
the log says exactly which calls, in which order, with which arguments, the renderer will
have to carry. Stage two serialises the same calls down the socket to the shell.

Usage: gen_gles1.py <gl.h> <glext.h> > libgles_cm.c
"""
import re
import sys

PROTO = re.compile(r'^GL_API\s+(.+?)\s*GL_APIENTRY\s+(gl\w+)\s*\((.*)\);\s*$')

def params(text):
    text = text.strip()
    if text in ('', 'void'):
        return []
    out = []
    for i, p in enumerate(text.split(',')):
        p = p.strip()
        # "const GLvoid *pixels" -> type "const GLvoid *", name "pixels"; unnamed -> a<i>
        m = re.match(r'^(.*?)(\**)\s*(\w+)?\s*(\[\d*\])?$', p)
        typ = (m.group(1).strip() + ' ' + m.group(2)).strip()
        name = m.group(3) or f'a{i}'
        if name in ('GLenum', 'GLint', 'GLuint', 'GLfloat', 'GLfixed', 'GLsizei', 'GLvoid', 'GLboolean', 'GLclampf', 'GLclampx', 'GLintptr', 'GLsizeiptr', 'GLbitfield', 'GLshort', 'GLubyte', 'GLbyte'):
            # a parameter with a type and no name
            typ = (typ + ' ' + name).strip(); name = f'a{i}'
        arr = m.group(4) or ''
        out.append((typ, name, arr))
    return out

def fmt(typ, name, arr=''):
    t = typ.replace('const', '').strip()
    if '*' in t or arr: return '%p', f'(const void*){name}'
    if t in ('GLfloat', 'GLclampf'): return '%g', f'(double){name}'
    if t in ('GLuint', 'GLenum', 'GLbitfield', 'GLsizei', 'GLint', 'GLfixed', 'GLclampx', 'GLboolean', 'GLshort', 'GLubyte', 'GLbyte', 'GLintptr', 'GLsizeiptr'):
        return '0x%x', f'(unsigned){name}'
    return '%ld', f'(long){name}'

def main():
    protos = []
    seen = set()
    for path in sys.argv[1:]:
        for line in open(path):
            m = PROTO.match(line.strip())
            if not m: continue
            ret, name, args = m.group(1).strip(), m.group(2), m.group(3)
            if name in seen: continue
            seen.add(name)
            protos.append((ret, name, params(args)))
    print('/* Generated by gen_gles1.py from the PDK\'s GLES/gl.h and glext.h: do not edit. */')
    print('#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>')
    print('#include <GLES/gl.h>\ntypedef void *GLeglImageOES;\n#include <GLES/glext.h>')
    print('''
static int log_limit(const char *name, unsigned *count) {
    static const char *quiet = NULL;
    if (!quiet) { quiet = getenv("LUNACY_GL_QUIET"); if (!quiet) quiet = ""; }
    (*count)++;
    if (*quiet) return 0;
    return *count <= 3;   /* the first three of each call go to the log */
}
static GLenum gl_error = GL_NO_ERROR;
static GLuint next_name = 1;
static GLint viewport[4] = { 0, 0, 1024, 768 };
static GLint scissor[4] = { 0, 0, 1024, 768 };
static void gen(GLsizei n, GLuint *out) { while (n-- > 0) *out++ = next_name++; }
''')
    for ret, name, ps in protos:
        sig = ', '.join(f'{t} {n}{a}' for t, n, a in ps) or 'void'
        print(f'{ret} {name}({sig}) {{')
        print(f'    static unsigned calls_;')
        if ps:
            f = ' '.join(f'{n}=' + fmt(t, n, a)[0] for t, n, a in ps)
            v = ', '.join(fmt(t, n, a)[1] for t, n, a in ps)
            print(f'    if (log_limit("{name}", &calls_)) fprintf(stderr, "[gl] {name} {f}\\n", {v});')
        else:
            print(f'    if (log_limit("{name}", &calls_)) fprintf(stderr, "[gl] {name}\\n");')
        # Answers the game reads.
        if name == 'glGetError':
            print('    { GLenum e = gl_error; gl_error = GL_NO_ERROR; return e; }')
        elif name == 'glGetString':
            # Writable copies: a game may tokenise the extension string in place.
            print('    static char vendor[] = "Lunacy", renderer[] = "Lunacy GLES 1.1 log", version[] = "OpenGL ES-CM 1.1", extensions[] = "GL_OES_framebuffer_object GL_OES_compressed_ETC1_RGB8_texture GL_OES_draw_texture GL_OES_texture_npot GL_OES_blend_subtract GL_OES_point_sprite", none[] = "";')
            print('    switch (name) { case GL_VENDOR: return (const GLubyte*)vendor; case GL_RENDERER: return (const GLubyte*)renderer; case GL_VERSION: return (const GLubyte*)version; case GL_EXTENSIONS: return (const GLubyte*)extensions; default: return (const GLubyte*)none; }')
        elif name in ('glGenTextures', 'glGenBuffers', 'glGenFramebuffersOES', 'glGenRenderbuffersOES'):
            print(f'    gen({ps[0][1]}, {ps[1][1]});')
        elif name == 'glGetIntegerv':
            print('    switch (pname) { case GL_MAX_TEXTURE_SIZE: *params = 2048; break; case GL_VIEWPORT: memcpy(params, viewport, sizeof viewport); break; case GL_SCISSOR_BOX: memcpy(params, scissor, sizeof scissor); break; case GL_MAX_TEXTURE_UNITS: *params = 2; break; case GL_DEPTH_BITS: *params = 16; break; case GL_STENCIL_BITS: *params = 8; break; case GL_RED_BITS: case GL_GREEN_BITS: case GL_BLUE_BITS: case GL_ALPHA_BITS: *params = 8; break; case GL_MAX_LIGHTS: *params = 8; break; case GL_NUM_COMPRESSED_TEXTURE_FORMATS: *params = 1; break; case GL_COMPRESSED_TEXTURE_FORMATS: *params = 0x8D64; break; default: *params = 0; }')
        elif name == 'glGetFloatv':
            print('    switch (pname) { case GL_ALIASED_POINT_SIZE_RANGE: case GL_ALIASED_LINE_WIDTH_RANGE: case GL_SMOOTH_POINT_SIZE_RANGE: case GL_SMOOTH_LINE_WIDTH_RANGE: params[0] = 1; params[1] = 64; break; default: *params = 0; }')
        elif name == 'glGetBooleanv':
            print('    *params = GL_FALSE;')
        elif name == 'glViewport':
            print('    viewport[0] = x; viewport[1] = y; viewport[2] = width; viewport[3] = height;')
        elif name == 'glScissor':
            print('    scissor[0] = x; scissor[1] = y; scissor[2] = width; scissor[3] = height;')
        elif name == 'glCheckFramebufferStatusOES':
            print('    return GL_FRAMEBUFFER_COMPLETE_OES;')
        elif name in ('glIsTexture', 'glIsBuffer', 'glIsEnabled', 'glIsFramebufferOES', 'glIsRenderbufferOES'):
            print('    return GL_TRUE;')
        elif name == 'glQueryMatrixxOES':
            print('    return 0;')
        elif ret != 'void':
            print(f'    return ({ret})0;')
        print('}')

if __name__ == '__main__':
    main()
