#!/bin/sh
# Records db8's replies on a TouchPad: run it there (novacom put, then sh) as the probe app.
# Each call prints "== <label>" then luna-send's replies. See Docs/db8.md.
A=org.webosarchive.lunacy.probe
K=org.webosarchive.lunacy.probe.test:1
c() { echo "== $1"; shift; luna-send -n 1 -a $A "palm://com.palm.db/$1" "$2" 2>&1; }

c "delKind (cleanup)" delKind "{\"id\":\"$K\"}"
c "putKind" putKind "{\"id\":\"$K\",\"owner\":\"$A\",\"indexes\":[{\"name\":\"byName\",\"props\":[{\"name\":\"name\"}]},{\"name\":\"byAgeName\",\"props\":[{\"name\":\"age\"},{\"name\":\"name\"}]}]}"
c "putKind wrong owner" putKind "{\"id\":\"org.other.kind:1\",\"owner\":\"org.other\"}"
echo "== put 3"; P=$(luna-send -n 1 -a $A palm://com.palm.db/put "{\"objects\":[{\"_kind\":\"$K\",\"name\":\"carol\",\"age\":30},{\"_kind\":\"$K\",\"name\":\"alice\",\"age\":25},{\"_kind\":\"$K\",\"name\":\"bob\",\"age\":30,\"tags\":[\"x\",\"y\"]}]}" 2>&1); echo "$P"
ID=$(echo "$P" | sed -n 's/.*"id": *"\([^"]*\)".*/\1/p' | head -1)
c "get by id" get "{\"ids\":[\"$ID\"]}"
c "merge by id" merge "{\"objects\":[{\"_id\":\"$ID\",\"nick\":\"cc\"}]}"
c "get after merge" get "{\"ids\":[\"$ID\"]}"
c "put replace by id" put "{\"objects\":[{\"_id\":\"$ID\",\"_kind\":\"$K\",\"name\":\"carol\",\"age\":33}]}"
c "get after put" get "{\"ids\":[\"$ID\"]}"
c "del by id" del "{\"ids\":[\"$ID\"]}"
c "del by id purge" del "{\"ids\":[\"$ID\"],\"purge\":true}"
c "put no kind" put "{\"objects\":[{\"name\":\"x\"}]}"
c "put unknown kind" put "{\"objects\":[{\"_kind\":\"org.nope:1\",\"name\":\"x\"}]}"
c "find all" find "{\"query\":{\"from\":\"$K\"}}"
c "find orderBy name" find "{\"query\":{\"from\":\"$K\",\"orderBy\":\"name\"}}"
c "find orderBy name desc limit 2" find "{\"query\":{\"from\":\"$K\",\"orderBy\":\"name\",\"desc\":true,\"limit\":2}}"
c "find where name = bob" find "{\"query\":{\"from\":\"$K\",\"where\":[{\"prop\":\"name\",\"op\":\"=\",\"val\":\"bob\"}]}}"
c "find where name prefix" find "{\"query\":{\"from\":\"$K\",\"where\":[{\"prop\":\"name\",\"op\":\"%\",\"val\":\"a\"}]}}"
c "find where age = 30 orderBy name" find "{\"query\":{\"from\":\"$K\",\"where\":[{\"prop\":\"age\",\"op\":\"=\",\"val\":30}],\"orderBy\":\"name\"}}"
c "find where age > 26" find "{\"query\":{\"from\":\"$K\",\"where\":[{\"prop\":\"age\",\"op\":\">\",\"val\":26}]}}"
c "find where name in list" find "{\"query\":{\"from\":\"$K\",\"where\":[{\"prop\":\"name\",\"op\":\"=\",\"val\":[\"alice\",\"bob\"]}]}}"
c "find no index (tags)" find "{\"query\":{\"from\":\"$K\",\"where\":[{\"prop\":\"tags\",\"op\":\"=\",\"val\":\"x\"}]}}"
c "find orderBy without index" find "{\"query\":{\"from\":\"$K\",\"orderBy\":\"age\"}}"
c "find select" find "{\"query\":{\"from\":\"$K\",\"select\":[\"name\"],\"orderBy\":\"name\"}}"
c "find count" find "{\"query\":{\"from\":\"$K\"},\"count\":true}"
c "find limit 1 (page)" find "{\"query\":{\"from\":\"$K\",\"orderBy\":\"name\",\"limit\":1}}"
c "find unknown kind" find "{\"query\":{\"from\":\"org.nope:1\"}}"
c "find filter (op on non-index)" find "{\"query\":{\"from\":\"$K\",\"where\":[{\"prop\":\"name\",\"op\":\"=\",\"val\":\"bob\"}],\"filter\":[{\"prop\":\"age\",\"op\":\"=\",\"val\":30}]}}"
c "search" search "{\"query\":{\"from\":\"$K\",\"where\":[{\"prop\":\"age\",\"op\":\"=\",\"val\":30}]}}"
c "get missing" get "{\"ids\":[\"nope\"]}"
c "del query age 25" del "{\"query\":{\"from\":\"$K\",\"where\":[{\"prop\":\"name\",\"op\":\"=\",\"val\":\"alice\"}]}}"
c "find after del" find "{\"query\":{\"from\":\"$K\",\"orderBy\":\"name\"}}"
c "find incDel" find "{\"query\":{\"from\":\"$K\",\"orderBy\":\"name\",\"incDel\":true}}"
c "merge query" merge "{\"query\":{\"from\":\"$K\",\"where\":[{\"prop\":\"name\",\"op\":\"=\",\"val\":\"bob\"}]},\"props\":{\"age\":31}}"
c "reserveIds" reserveIds "{\"count\":2}"
c "batch" batch "{\"operations\":[{\"method\":\"put\",\"params\":{\"objects\":[{\"_kind\":\"$K\",\"name\":\"dave\",\"age\":40}]}},{\"method\":\"find\",\"params\":{\"query\":{\"from\":\"$K\",\"orderBy\":\"name\"}}}]}"
c "getProperties" getProperties "{\"id\":\"$K\"}"
c "bad method" nosuchmethod "{}"
c "find bad json query" find "{\"query\":{}}"
c "delKind" delKind "{\"id\":\"$K\"}"
c "find after delKind" find "{\"query\":{\"from\":\"$K\"}}"
