#!/usr/bin/env python3
"""Generates app/src/main/assets/lunacy/fonts.css: @font-face rules that give every page the
Prelude family names webOS had installed as system fonts. Re-run when fonts change."""
import os
FONTS = os.path.join(os.path.dirname(__file__), "../app/src/main/assets/luna/fonts")
OUT = os.path.join(os.path.dirname(__file__), "../app/src/main/assets/lunacy/fonts.css")
have = set(os.listdir(FONTS))
rules = []

def face(family, weight, style, f):
    if f in have:
        rules.append(f'@font-face{{font-family:"{family}";font-weight:{weight};font-style:{style};src:url("/__lunacy/fonts/{f}")}}')

# Weighted families: CSS weight -> file suffix.
WGL = {300: "Light", 400: "Medium", 500: "Medium", 700: "Bold", 900: "Black"}
for fam in ("PreludeWGL", "PreludeCompWGL", "PreludeCondWGL"):
    for w, n in WGL.items():
        face(fam, w, "normal", f"{fam}-{n}.ttf")
        face(fam, w, "italic", f"{fam}-{n}Italic.ttf")
    # Full names ("PreludeWGL Light", "PreludeWGL-Light") pin one face; bold asks for Bold.
    for n in set(WGL.values()):
        for alias in (f"{fam} {n}", f"{fam}-{n}"):
            face(alias, "normal", "normal", f"{fam}-{n}.ttf")
            face(alias, "normal", "italic", f"{fam}-{n}Italic.ttf")
            face(alias, "bold", "normal", f"{fam}-Bold.ttf" if n in ("Light", "Medium") else f"{fam}-{n}.ttf")

for w, n in {400: "Medium", 500: "Medium", 700: "Bold"}.items():
    face("Prelude", w, "normal", f"Prelude-{n}.ttf")
    face("Prelude", w, "italic", f"Prelude-{n}Oblique.ttf")
    for fam in ("PreludeCondensed", "Prelude Condensed"):
        face(fam, w, "normal", f"PreludeCondensed-{n}.ttf")
for n in ("Medium", "Bold"):
    for alias in (f"Prelude {n}", f"Prelude-{n}"):
        face(alias, "normal", "normal", f"Prelude-{n}.ttf")
        face(alias, "normal", "italic", f"Prelude-{n}Oblique.ttf")
        face(alias, "bold", "normal", "Prelude-Bold.ttf")

# Apps that quoted a whole fallback list as one family name, e.g.
# font-family: "PreludeWGL Light, Arial, Helvetica, sans-serif". webOS still resolved these.
for n in ("Light", "Bold"):
    face(f"PreludeWGL {n}, Arial, Helvetica, sans-serif", "normal", "normal", f"PreludeWGL-{n}.ttf")

with open(OUT, "w") as o:
    o.write("/* Generated by tools/gen-fonts-css.py. The Prelude fonts, as webOS had them installed. */\n")
    o.write("\n".join(rules) + "\n")
    # webOS's default font was Prelude; app CSS that names its own font still wins.
    o.write("html{font-family:Prelude,sans-serif}\n")
print(len(rules), "rules")
